#ifndef DEBUG_H
#define DEBUG_H

#include <QLoggingCategory>

Q_DECLARE_LOGGING_CATEGORY(TS);
Q_DECLARE_LOGGING_CATEGORY(SERVER);
Q_DECLARE_LOGGING_CATEGORY(CLIENT);
Q_DECLARE_LOGGING_CATEGORY(CLIENT_IO);
Q_DECLARE_LOGGING_CATEGORY(DELUGE);
Q_DECLARE_LOGGING_CATEGORY(DELUGE_IO);
Q_DECLARE_LOGGING_CATEGORY(DATABASE);

#endif