#ifndef DEBUG_H
#define DEBUG_H

#include <QLoggingCategory>

Q_DECLARE_LOGGING_CATEGORY(TS);
Q_DECLARE_LOGGING_CATEGORY(SERVER);
Q_DECLARE_LOGGING_CATEGORY(CLIENT);
Q_DECLARE_LOGGING_CATEGORY(CLIENT_IO);
Q_DECLARE_LOGGING_CATEGORY(DELUGE);
Q_DECLARE_LOGGING_CATEGORY(TORRENTSERVICE_IO);
Q_DECLARE_LOGGING_CATEGORY(DATABASE);
Q_DECLARE_LOGGING_CATEGORY(TRANSFER);
Q_DECLARE_LOGGING_CATEGORY(TASK);
Q_DECLARE_LOGGING_CATEGORY(TASKS);

#endif
