#include "debug.h"

Q_LOGGING_CATEGORY(TS, "ts");
Q_LOGGING_CATEGORY(SERVER, "ts.server");
Q_LOGGING_CATEGORY(CLIENT, "ts.client");
Q_LOGGING_CATEGORY(CLIENT_IO, "ts.client.io");
Q_LOGGING_CATEGORY(DELUGE, "ts.deluge");
Q_LOGGING_CATEGORY(TORRENTSERVICE_IO, "ts.torrentservice.io");
Q_LOGGING_CATEGORY(DATABASE, "ts.database");
Q_LOGGING_CATEGORY(TRANSFER, "ts.transfer");
Q_LOGGING_CATEGORY(TASK, "ts.task");
Q_LOGGING_CATEGORY(TASKS, "ts.tasks");