#include "debug.h"

Q_LOGGING_CATEGORY(TS, "ts");
Q_LOGGING_CATEGORY(SERVER, "ts.server");
Q_LOGGING_CATEGORY(CLIENT, "ts.client");
Q_LOGGING_CATEGORY(CLIENT_IO, "ts.client.io");
Q_LOGGING_CATEGORY(DELUGE, "ts.deluge");
Q_LOGGING_CATEGORY(DELUGE_IO, "ts.deluge.io");
Q_LOGGING_CATEGORY(DATABASE, "ts.database");